# Generated by Django 3.1.4 on 2021-01-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210124_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=122),
        ),
    ]
